name: Run tests on all packages

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  run-tests:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        package:
          - evo-sdk-common
          - evo-blockmodel
          - evo-files
          - evo-objects
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/testing
        with:
          PYTHON_VERSION: ${{ matrix.python-version }}
          PACKAGE: ${{ matrix.package}}
